version: '2'
services:
  mysql:
    container_name: mysql-example
    restart: always
    image: mysql:latest
    ports:
     - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'root-secret'
      MYSQL_DATABASE: 'test_schema'
      MYSQL_USER: 'test'
      MYSQL_PASSWORD: 'secret'
    volumes:
      - my-datavolume:/var/lib/mysql 
volumes:
  my-datavolume:
