version: '2'
services:
  mysql:
    container_name: mysql-db
    restart: always
    image: mysql:latest
    ports:
     - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'root-secret'
      MYSQL_DATABASE: 'test-db'
      MYSQL_USER: 'test'
      MYSQL_PASSWORD: 'secret'
    volumes:
      - ./mysql-data:/var/lib/mysql
